In [1]:
1+1

2

In [2]:
print('hello world')

hello world

In [2]:
! pip install pandas matplotlib seaborn

Collecting pandas
  Downloading pandas-3.0.3-cp313-cp313-win_amd64.whl.metadata (19 kB)
Collecting matplotlib
  Downloading matplotlib-3.11.0-cp313-cp313-win_amd64.whl.metadata (80 kB)
Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\Dell\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Dell\AppData\Roaming\Python\Python313\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.3.3-cp313-cp313-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Downloading fonttools-4.63.0-cp313-cp313-win_amd64.whl.metadata (121 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.5.0-cp313-cp313-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: packaging>=20.0 in C:\Users\Dell\AppData\Roaming\Python\Python313\site-packages (from matplotlib) (26.2)
Collecting pillow>=9 (from matplotlib)
  Downloading pillow-12.2.0-cp313-cp313-win_amd64.whl.metadata (9.0 kB)
Collecting pyparsing>=3 (from matplotlib)
  Downloading pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: six>=1.5 in C:\Users\Dell\AppData\Roaming\Python\Python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp313-cp313-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ------------------- -------------------- 4.7/9.8 MB 21.8 MB/s eta 0:00:01
   ---------------------------------- ----- 8.4/9.8 MB 19.7 MB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 16.7 MB/s  0:00:00
Downloading matplotlib-3.11.0-cp313-cp313-win_amd64.whl (9.3 MB)
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ------------- -------------------------- 3.1/9.3 MB 15.8 MB/s eta 0:00:01
   ------------------------- -------------- 6.0/9.3 MB 14.8 MB/s eta 0:00:01
   ------------------------------- -------- 7.3/9.3 MB 11.6 MB/s eta 0:00:01
   ---------------------------------------  9.2/9.3 MB 11.0 MB/s eta 0:00:01
   ---------------------------------------- 9.3/9.3 MB 10.1 MB/s  0:00:00
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
Downloading contourpy-1.3.3-cp313-cp313-win_amd64.whl (226 kB)
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.63.0-cp313-cp313-win_amd64.whl (2.3 MB)
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ----------------------------------- ---- 2.1/2.3 MB 9.8 MB/s eta 0:00:01
   ---------------------------------------- 2.3/2.3 MB 9.3 MB/s  0:00:00
Downloading kiwisolver-1.5.0-cp313-cp313-win_amd64.whl (73 kB)
Downloading pillow-12.2.0-cp313-cp313-win_amd64.whl (7.1 MB)
   ---------------------------------------- 0.0/7.1 MB ? eta -:--:--
   ----------- ---------------------------- 2.1/7.1 MB 10.2 MB/s eta 0:00:01
   -------------------------- ------------- 4.7/7.1 MB 10.9 MB/s eta 0:00:01
   ---------------------------------------  7.1/7.1 MB 11.3 MB/s eta 0:00:01
   ---------------------------------------- 7.1/7.1 MB 10.0 MB/s  0:00:00
Downloading pyparsing-3.3.2-py3-none-any.whl (122 kB)
Downloading tzdata-2026.2-py2.py3-none-any.whl (349 kB)
Installing collected packages: tzdata, pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, pandas, matplotlib, seaborn

   ----------------------------------------  0/10 [tzdata]
   ----------------------------------------  0/10 [tzdata]
   ---- -----------------------------------  1/10 [pyparsing]
   ---- -----------------------------------  1/10 [pyparsing]
   -------- -------------------------------  2/10 [pillow]
   -------- -------------------------------  2/10 [pillow]
   -------- -------------------------------  2/10 [pillow]
   -------- -------------------------------  2/10 [pillow]
   -------- -------------------------------  2/10 [pillow]
   -------- -------------------------------  2/10 [pillow]
   -------- -------------------------------  2/10 [pillow]
   -------- -------------------------------  2/10 [pillow]
   -------- -------------------------------  2/10 [pillow]
   -------- -------------------------------  2/10 [pillow]
   -------- -------------------------------  2/10 [pillow]
   ---------------- -----------------------  4/10 [fonttools]
   ---------------- -----------------------  4/10 [fonttools]
   ---------------- -----------------------  4/10 [fonttools]
   ---------------- -----------------------  4/10 [fonttools]
   ---------------- -----------------------  4/10 [fonttools]
   ---------------- -----------------------  4/10 [fonttools]
   ---------------- -----------------------  4/10 [fonttools]
   ---------------- -----------------------  4/10 [fonttools]
   ---------------- -----------------------  4/10 [fonttools]
   ---------------- -----------------------  4/10 [fonttools]
   ---------------- -----------------------  4/10 [fonttools]
   ---------------- -----------------------  4/10 [fonttools]
   ---------------- -----------------------  4/10 [fonttools]
   ---------------- -----------------------  4/10 [fonttools]
   ---------------- -----------------------  4/10 [fonttools]
   ---------------- -----------------------  4/10 [fonttools]
   ---------------- -----------------------  4/10 [fonttools]
   ---------------- -----------------------  4/10 [fonttools]
   ---------------- -----------------------  4/10 [fonttools]
   ---------------- -----------------------  4/10 [fonttools]
   ---------------- -----------------------  4/10 [fonttools]
   ---------------- -----------------------  4/10 [fonttools]
   ---------------- -----------------------  4/10 [fonttools]
   ---------------- -----------------------  4/10 [fonttools]
   ---------------- -----------------------  4/10 [fonttools]
   ---------------- -----------------------  4/10 [fonttools]
   ---------------- -----------------------  4/10 [fonttools]
   ---------------- -----------------------  4/10 [fonttools]
   ---------------- -----------------------  4/10 [fonttools]
   ---------------- -----------------------  4/10 [fonttools]
   ---------------- -----------------------  4/10 [fonttools]
   ---------------- -----------------------  4/10 [fonttools]
   ---------------- -----------------------  4/10 [fonttools]
   ---------------- -----------------------  4/10 [fonttools]
   ---------------- -----------------------  4/10 [fonttools]
   ---------------- -----------------------  4/10 [fonttools]
   ---------------- -----------------------  4/10 [fonttools]
   ---------------- -----------------------  4/10 [fonttools]
   ---------------- -----------------------  4/10 [fonttools]
   ---------------- -----------------------  4/10 [fonttools]
   ---------------- -----------------------  4/10 [fonttools]
   ---------------- -----------------------  4/10 [fonttools]
   ---------------- -----------------------  4/10 [fonttools]
   ---------------- -----------------------  4/10 [fonttools]
   ---------------- -----------------------  4/10 [fonttools]
   ---------------- -----------------------  4/10 [fonttools]
   ---------------- -----------------------  4/10 [fonttools]
   ------------------------ ---------------  6/10 [contourpy]
   ------------------------ ---------------  6/10 [contourpy]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   -------------------------------- -------  8/10 [matplotlib]
   -------------------------------- -------  8/10 [matplotlib]
   -------------------------------- -------  8/10 [matplotlib]
   -------------------------------- -------  8/10 [matplotlib]
   -------------------------------- -------  8/10 [matplotlib]
   -------------------------------- -------  8/10 [matplotlib]
   -------------------------------- -------  8/10 [matplotlib]
   -------------------------------- -------  8/10 [matplotlib]
   -------------------------------- -------  8/10 [matplotlib]
   -------------------------------- -------  8/10 [matplotlib]
   -------------------------------- -------  8/10 [matplotlib]
   -------------------------------- -------  8/10 [matplotlib]
   -------------------------------- -------  8/10 [matplotlib]
   -------------------------------- -------  8/10 [matplotlib]
   -------------------------------- -------  8/10 [matplotlib]
   -------------------------------- -------  8/10 [matplotlib]
   -------------------------------- -------  8/10 [matplotlib]
   -------------------------------- -------  8/10 [matplotlib]
   -------------------------------- -------  8/10 [matplotlib]
   -------------------------------- -------  8/10 [matplotlib]
   -------------------------------- -------  8/10 [matplotlib]
   -------------------------------- -------  8/10 [matplotlib]
   -------------------------------- -------  8/10 [matplotlib]
   -------------------------------- -------  8/10 [matplotlib]
   -------------------------------- -------  8/10 [matplotlib]
   -------------------------------- -------  8/10 [matplotlib]

In [4]:
! pip show pandas numpy

Name: pandas
Version: 3.0.3
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: https://pandas.pydata.org
Author:
Author-email: The Pandas Development Team <pandas-dev@python.org>
License: BSD 3-Clause License

 Copyright (c) 2008-2011, AQR Capital Management, LLC, Lambda Foundry, Inc. and PyData Development Team
 All rights reserved.

 Copyright (c) 2011-2026, Open source contributors.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:

 * Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

 * Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

 * Neither the name of the copyright holder nor the names of its
   contributors may be used to endorse or promote products derived from
   this software without specific prior written permission.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

Location: C:\Users\Dell\AppData\Local\Programs\Python\Python313\Lib\site-packages
Requires: numpy, python-dateutil, tzdata
Required-by: seaborn
---
Name: numpy
Version: 2.5.0
Summary: Fundamental package for array computing in Python
Home-page: https://numpy.org
Author: Travis E. Oliphant et al.
Author-email:
License-Expression: BSD-3-Clause AND 0BSD AND MIT AND Zlib AND CC0-1.0
Location: C:\Users\Dell\AppData\Local\Programs\Python\Python313\Lib\site-packages
Requires:
Required-by: contourpy, matplotlib, pandas, seaborn

* exercise mentioned in PPT

In [ ]:


# considering the list with deplicates of dictionary items , and  *** deduplicating them 

l = [ {'a':1} , {'b':2} , {'c':3} , {'a':1}]  # noqa: E741
l1 = []
uniques = set()
for i in l:
    t = (tuple(i.items()))
    if t not in uniques:
        uniques.add(t)
        l1.append(i)

print(uniques)
print(l1)

{(('a', 1),), (('c', 3),), (('b', 2),)}
[{'a': 1}, {'b': 2}, {'c': 3}]

In [24]:
l_comp = [ data.items() for data in l if 'a' in data.keys()  ]
print(l_comp)

[dict_items([('a', 1)]), dict_items([('a', 1)])]

In [21]:
for data in l :
  
    if 'a' in data.keys() :
        print('matched key is :')
        print(data.items())

matched key is :
dict_items([('a', 1)])
matched key is :
dict_items([('a', 1)])

In [27]:
# missing key function 

l = [ {'a':1} , {'b':2} , {'':3} , {'a':1}]  # noqa: E741


def missing_key( s ):
    missingkey = [data.items() for data in s if '' in  data.keys()]

    return missingkey

print(missing_key(l))

[dict_items([('', 3)])]

* list comprehension

In [ ]:
#    LIST COMPREHENSIONS

squares = [ {x:x**2} for x in range(5)]
squares

[{0: 0}, {1: 1}, {2: 4}, {3: 9}, {4: 16}]

In [32]:
even_squares = [ {x:x**2 for x in range(5) if x%2==0}]
even_squares

[{0: 0, 2: 4, 4: 16}]

In [ ]:
l1 = [1,2,3,4,5]
l2 = ['a','b','c','d','e']

make_dic = [ {i:j} for i , j in zip(l2,l1) ]   # zip function to map 2 lists based on their index 
make_dic

[{'a': 1}, {'b': 2}, {'c': 3}, {'d': 4}, {'e': 5}]

* dictionary comprehensions

In [41]:
dic = {'arun': 1, 'barath': 2, 'chandu': 3, 'dany': 4,'eshwar': 5}
swapped_dic = { value : key for key , value in dic.items()}

print(swapped_dic)

{1: 'arun', 2: 'barath', 3: 'chandu', 4: 'dany', 5: 'eshwar'}

In [44]:
# create uppercase keys or values 

upper_case = { value.upper() : key for key , value in swapped_dic.items()}
upper_case

{'ARUN': 1, 'BARATH': 2, 'CHANDU': 3, 'DANY': 4, 'ESHWAR': 5}

In [46]:
# conditional dictionaries

d = { x: { 'even' if x%2==0 else 'odd'} for x in range(5) }
d

{0: {'even'}, 1: {'odd'}, 2: {'even'}, 3: {'odd'}, 4: {'even'}}

*  Generators

In [ ]:
# INSTEAD OF RETURN IT YEILDS THE OUTOUT ONE AT A TIME WITHOUT USING MORE MEMORY

def gen():
    for i in range(16):
        yield i
a = gen()

print(next(a))
print(next(a))

0
1

In [11]:
def gen():
    yield 10
    yield 20
    yield 30

a = gen()

print(next(a))
print(next(a))
print(next(a))

10
20
30

In [14]:
a = ( x for x in range(10))
print(next(a))
print(next(a))
print(next(a))
print(next(a))
print(next(a))
print(next(a))
print(next(a))
print(next(a))
print(a)

0
1
2
3
4
5
6
7
<generator object <genexpr> at 0x0000022A41F51A80>

In [2]:
! pip install pandas

Collecting pandas
  Downloading pandas-3.0.3-cp311-cp311-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.4.6-cp311-cp311-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Dell\anaconda3\envs\myenv\Lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Using cached tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in C:\Users\Dell\anaconda3\envs\myenv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp311-cp311-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ----- ---------------------------------- 1.3/9.9 MB 9.5 MB/s eta 0:00:01
   ------------------- -------------------- 4.7/9.9 MB 13.6 MB/s eta 0:00:01
   -------------------------------- ------- 8.1/9.9 MB 14.0 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 12.9 MB/s  0:00:00
Downloading numpy-2.4.6-cp311-cp311-win_amd64.whl (12.6 MB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ----- ---------------------------------- 1.8/12.6 MB 8.4 MB/s eta 0:00:02
   -------------- ------------------------- 4.7/12.6 MB 10.9 MB/s eta 0:00:01
   ----------------------- ---------------- 7.3/12.6 MB 11.3 MB/s eta 0:00:01
   ---------------------------- ----------- 8.9/12.6 MB 10.2 MB/s eta 0:00:01
   ------------------------------------- -- 11.8/12.6 MB 10.9 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 10.5 MB/s  0:00:01
Using cached tzdata-2026.2-py2.py3-none-any.whl (349 kB)
Installing collected packages: tzdata, numpy, pandas

   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   ---------------------------------------- 3/3 [pandas]

Successfully installed numpy-2.4.6 pandas-3.0.3 tzdata-2026.2

In [4]:
import pandas as pd

s = pd.Series([10, 20, 30])
print(s)

0    10
1    20
2    30
dtype: int64

In [5]:
data = {
    "name": ["A", "B", "C"],
    "age": [20, 21, 22]
}

df = pd.DataFrame(data)
print(df)

  name  age
0    A   20
1    B   21
2    C   22

In [7]:
# Basic operations 


df.head(2)

  name  age
0    A   20
1    B   21

In [8]:
df.tail(2)

  name  age
1    B   21
2    C   22

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      str
 1   age     3 non-null      int64
dtypes: int64(1), str(1)
memory usage: 180.0 bytes

In [11]:
df.describe()

        age
count   3.0
mean   21.0
std     1.0
min    20.0
25%    20.5
50%    21.0
75%    21.5
max    22.0

In [10]:
# selecting a column

df['age']

0    20
1    21
2    22
Name: age, dtype: int64

In [12]:
df.dropna()        # remove missing values
df.fillna(0)       # replace missing values
df.rename(columns={"age": "Age"})

  name  Age
0    A   20
1    B   21
2    C   22

In [14]:
df["salary"] = [1000, 2000, 3000]
df

  name  age  salary
0    A   20    1000
1    B   21    2000
2    C   22    3000

In [18]:
df['age'] = df['age'].astype(int)
df

  name  age  salary
0    A   20    1000
1    B   21    2000
2    C   22    3000